### ISSUE TITLE
24 example fails to compile

### ISSUE THREAD

**Issue by rustrust** [gluon-lang/gluon#955] opened 2023-07-20 00:05 UTC
is this project abandoned? can we get ci?

error[E0491]: in type `&mut QueryTable<'me, Q, <Q as AsyncQueryFunction<'_, 'me>>::SendDb>`, reference has a longer lifetime than the data it references
   --> /Users/username/.cargo/registry/src/index.crates.io-6f17d22bba15001f/gluon-salsa-0.15.2/src/lib.rs:696:28
    |
696 |     pub async fn get_async(&mut self, key: Q::Key) -> Q::Value {
    |                            ^^^^^^^^^
    |
note: the pointer is valid for the anonymous lifetime defined here
   --> /Users/username/.cargo/registry/src/index.crates.io-6f17d22bba15001f/gluon-salsa-0.15.2/src/lib.rs:696:28
    |
696 |     pub async fn get_async(&mut self, key: Q::Key) -> Q::Value {
    |                            ^^^^^^^^^
note: but the referenced data is only valid for the lifetime `'me` as defined here
   --> /Users/username/.cargo/registry/src/index.crates.io-6f17d22bba15001f/gluon-salsa-0.15.2/src/lib.rs:684:6
    |
684 | impl<'me, Q> QueryTable<'me, Q, <Q as QueryDb<'me>>::Db>
    |      ^^^

error[E0491]: in type `&mut QueryTable<'me, Q, <Q as AsyncQueryFunction<'_, 'me>>::SendDb>`, reference has a longer lifetime than the data it references
   --> /Users/username/.cargo/registry/src/index.crates.io-6f17d22bba15001f/gluon-salsa-0.15.2/src/lib.rs:703:9
    |
703 |         &mut self,
    |         ^^^^^^^^^
    |
note: the pointer is valid for the anonymous lifetime defined here
   --> /Users/username/.cargo/registry/src/index.crates.io-6f17d22bba15001f/gluon-salsa-0.15.2/src/lib.rs:703:9
    |
703 |         &mut self,
    |         ^^^^^^^^^
note: but the referenced data is only valid for the lifetime `'me` as defined here
   --> /Users/username/.cargo/registry/src/index.crates.io-6f17d22bba15001f/gluon-salsa-0.15.2/src/lib.rs:684:6
    |
684 | impl<'me, Q> QueryTable<'me, Q, <Q as QueryDb<'me>>::Db>
    |      ^^^

error[E0491]: in type `&QueryTable<'me, Q, <Q as AsyncQueryFunction<'_, 'me>>::SendDb>`, reference has a longer lifetime than the data it references
   --> /Users/username/.cargo/registry/src/index.crates.io-6f17d22bba15001f/gluon-salsa-0.15.2/src/lib.rs:714:18
    |
714 |     pub fn purge(&self)
    |                  ^^^^^
    |
note: the pointer is valid for the anonymous lifetime defined here
   --> /Users/username/.cargo/registry/src/index.crates.io-6f17d22bba15001f/gluon-salsa-0.15.2/src/lib.rs:714:18
    |
714 |     pub fn purge(&self)
    |                  ^^^^^
note: but the referenced data is only valid for the lifetime `'me` as defined here
   --> /Users/username/.cargo/registry/src/index.crates.io-6f17d22bba15001f/gluon-salsa-0.15.2/src/lib.rs:684:6
    |
684 | impl<'me, Q> QueryTable<'me, Q, <Q as QueryDb<'me>>::Db>
    |      ^^^

For more information about this error, try `rustc --explain E0491`.
error: could not compile `gluon-salsa` (lib) due to 3 previous errors

**Comment by Marwes** [comment] 2023-08-07 11:56
Closing as a duplicate of https://docs.rs/redis/latest/redis/aio/struct.MultiplexedConnection.html (error is a bug in rustc on newer compilers).

The project is not actively being developed anymore though, though I do try to keep it working.

**Closed by Marwes** 2023-08-07 11:56 UTC
