### ISSUE TITLE
Broken links on gluon-lang.org

### ISSUE THREAD

**Issue by Laegluin** [gluon-lang/gluon#730] opened 2019-05-12 21:38 UTC
Looks like the links to the gluon-std docs are broken, they both return a 404.

**Comment by Marwes** [comment] 2019-05-16 12:24
Looks like the documentation generation fails silently under some circumstances, haven't found the cause yet though.

**Comment by Marwes** [comment] 2019-05-19 12:01
Fixed now, sorry for the delay!

**Closed by Marwes** 2019-05-19 12:01 UTC
Labels: bug
